---
title: "Extended Data Figure 5"
author: "Sheldon Ding"
date: "2026-05-06"
output: html_document
---

```{r load libraries}
#packages (some packages might require dependent packages)
library(Matrix)
library(Seurat)
library(Signac)
library(patchwork)
library(tidyverse)
library(dplyr)
library(readr)
library(magrittr)
library(harmony)
library(clustree)
library(GenomicRanges)
library(msigdbr)
library(clusterProfiler)
library(IRanges)
library(Biostrings)
library(biomaRt)
library(DESeq2)
library(DESeq2)
library(scCustomize)
library(openxlsx)
library(rGREAT)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ComplexHeatmap)
library(circlize)
library(monocle3)
```

```{r set seed}
set.seed(6)
```

```{r load object}
OL_lineage <- readRDS("/output/objects/OL_lineage.RDS")

OPC <- readRDS("/output/objects/OPC.RDS")
```

```{r color}
postnatalcolor <- c("Fetal" = "#0D0887", "Postnatal" = "#F0F921")

cellcolor <- c("Fetal COP" = "#00FFFF", "OPC" = "#42A5F5", "Early OL" = "#0D47A1","OL" = "#37294f")
```

###Extended Data Figure 5
```{r Extended Data Figure 5a}
#RidgePlot of gene expression
RidgePlot(OL_lineage, group.by="Cell_Type", features=c("SOX2","YAP1","PDGFRA","OLIG1","OLIG2","SOX10","BCAS1","TCF7L2","PLP1","RBFOX1","CNP"), 
          fill.by = "ident",
          col=cellcolor,
          stack=T)
```

```{r Extended Data Figure 5b}
# DimPlot of Cell_Type population with umap.rna
DimPlot(OL_lineage, group.by = "Cell_Type", reduction = "umap.rna",cols = cellcolor)

# DimPlot of Cell_Type population with umap.atac
DimPlot(OL_lineage, group.by = "Cell_Type", reduction = "umap.atac", cols = cellcolor)
```

```{r Extended Data Figure 5c}
# DimPlot of fetal and postnatal cells with wnn.umap
DimPlot(OL_lineage, group.by = "postnatal", cols = postnatalcolor, reduction = "wnn.umap")
```

```{r Extended Data Figure 5d}
# Transcription factor foorprinting
OL_lineage <- Footprint(
  object = OL_lineage,
  motif.name = c("SOX10","SOX2","TEAD1","TCF4"),
  genome = BSgenome.Hsapiens.UCSC.hg38)


# plot the footprint data for each Cell_Type
Idents(OL_lineage) <- "Cell_Type"

PlotFootprint(OL_lineage,features = c("SOX10","SOX2","TEAD1","TCF4")) & scale_color_manual(values = cellcolor)
```

```{r Extended Data Figure 5e}
# create a metadata to denote fetal and postnatal OPC
OPC$Fetal.OPC <- case_when(
  OPC$Subtype %in% c("Early Fetal OPC", "Late Fetal OPC") & OPC$postnatal == "Fetal" ~ "Fetal OPC", OPC$Subtype == "Postnatal OPC" & OPC$postnatal == "Postnatal" ~ "Postnatal OPC", TRUE ~ "Other OPC")

OPC$Fetal.OPC <- factor(
  OPC$Fetal.OPC,
  levels = c("Fetal OPC", "Postnatal OPC", "Other OPC"))

DefaultAssay(OPC) <- "RNA"
Idents(OPC) <- "Fetal.OPC"

# calculate the DEG between Postnatal OPC and Fetal OPC
agg<-AggregateExpression(OPC,assays="RNA", return.seurat=F, group.by=c("sample_id","Fetal.OPC"))
pb <- agg$RNA
colnames(pb)<- gsub("-","_",colnames(pb))
meta <- OPC@meta.data[, c("Fetal.OPC","sample_id","dev.group","Sex","Race","postnatal")]

meta_unique <- meta[!duplicated(paste(meta$sample_id, meta$Fetal.OPC)), ]

meta_unique$colname <- paste(meta_unique$sample_id,
                             meta_unique$Fetal.OPC,
                             sep = "_") %>% gsub("-","_",.)
rownames(meta_unique) <- meta_unique$colname
rownames(meta_unique)[grep("10X",rownames(meta_unique))] <- paste0("g",rownames(meta_unique)[grep("10X",rownames(meta_unique))])
meta_unique <- meta_unique[colnames(pb), ]

cellcount<-table(OPC$Fetal.OPC,OPC$sample_id) %>% data.frame()
rownames(cellcount)<-paste(cellcount$Var2,cellcount$Var1,sep="_")
rownames(cellcount)[grep("10X", rownames(cellcount))] <- paste0("g",rownames(cellcount)[grep("10X", rownames(cellcount))]) 


meta_unique$CellCount<-cellcount[rownames(meta_unique),]$Freq

#check
all(rownames(meta_unique) == colnames(pb))

ct.1 <- "Postnatal OPC"
ct.2 <- "Fetal OPC"
keep <- (meta_unique$Fetal.OPC == ct.1 | meta_unique$Fetal.OPC == ct.2)

ct_counts <- pb[, keep]
ct_meta   <- meta_unique[keep, ]

ct_meta$dev.group <- factor(ct_meta$dev.group,
                            levels = c("Fetal","Infant","Child","Adolescent","Adult"))
ct_meta$Sex[is.na(ct_meta$Sex)] <- "NAFetal"
ct_meta$Sex <- factor(ct_meta$Sex)
ct_meta$Fetal.OPC <- factor(ct_meta$Fetal.OPC, levels = c(ct.2, ct.1))
dds <- DESeqDataSetFromMatrix(
  countData = round(ct_counts),
  colData = ct_meta,
  design = ~ Fetal.OPC
)

keep_genes <- rowSums(counts(dds)) >= 10
dds <- dds[keep_genes, ]

dds <- DESeq(dds)
vsd <- vst(dds)

res <- results(dds, name="Fetal.OPC_Postnatal.OPC_vs_Fetal.OPC")
res <- lfcShrink(dds,
                 coef="Fetal.OPC_Postnatal.OPC_vs_Fetal.OPC",
                 res=res, type = "normal")
res.df<-res %>% data.frame


res_tbl <- res %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

# set thresholds
padj_cutoff <- 0.05
res_table_thres <- res_tbl %>% 
  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1)

# set comparison direction
res_table_thres$direction <- ""
res_table_thres$direction[!is.na(sign(res_table_thres$log2FoldChange))] <- ifelse(sign(res_table_thres$log2FoldChange[!is.na(sign(res_table_thres$log2FoldChange))])==-1, yes = "down", no = "up")
res_table_thres$threshold[is.na(res_table_thres$threshold)]<-FALSE

Top_Hits <- head(arrange(res_table_thres, padj), 10)
Top_Hits <- rbind(Top_Hits, head(arrange(res_table_thres[res_table_thres$log2FoldChange >=1,], desc(log2FoldChange)), 5))

# Create the 'label' column: gene name for top hits, NULL otherwise
res_table_thres$label <- if_else(res_table_thres$gene %in% Top_Hits$gene, res_table_thres$gene, as.character(NA))

# top hits DEG beteen Postnatal OPC and Fetal OPC volcano plot
ggplot(data=res_table_thres, aes(x=log2FoldChange, y=-1*log10(padj), color=threshold)) +geom_point(size=1) + scale_color_manual(values= c("black","red3")) + geom_vline(xintercept = 1,linetype = "dashed")+geom_vline(xintercept = -1,linetype = "dashed")+geom_hline(yintercept = -1*log10(0.05),linetype = "dashed")+theme_bw() + ggrepel::geom_text_repel(
  aes(label = label),
  size = 3,        
  box.padding = 0.5,
  point.padding = 0.5,
  segment.color = 'grey50', 
  show.legend = FALSE,
  color="black"
)
```


















