---
title: "Extended Data Figure 4"
author: "Sheldon Ding"
date: "2026-05-06"
output: html_document
---

```{r load libraries}
#packages (some packages might require dependent packages)
library(Matrix)
library(Seurat)
library(Signac)
library(patchwork)
library(tidyverse)
library(dplyr)
library(readr)
library(magrittr)
library(harmony)
library(clustree)
library(GenomicRanges)
library(msigdbr)
library(clusterProfiler)
library(IRanges)
library(Biostrings)
library(biomaRt)
library(DESeq2)
library(DESeq2)
library(scCustomize)
library(openxlsx)
library(rGREAT)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ComplexHeatmap)
library(circlize)
```

```{r set seed}
set.seed(6)
```

```{r load object}
RGL_Astrocyte  <- readRDS("output/objects/atlas.RDS")
```

```{r color}
RGL_Astrocyte_subtype_color = c("Radial Glia" = "#e2e700", "CD44-hi Astrocyte" = "#FFA500","EAAT2-hi Astrocyte" = "#FF4F00","OL-like Astrocyte" = "#C2A162","Undetermined Astrocyte" = "#4F4F4F")

devcolor <- c("Fetal" = "#0D0887", "Infant" = "#7E03A8", "Child" ="#CC4678","Adolescent" = "#F89441","Adult" = "#F0F921")
```

###Extended Data Figure 4
```{r Extended Data Figure 4a}
# DimPlot of resolution of wsnn_res.0.2 with wnn.umap
DimPlot(RGL_Astrocyte, group.by = "wsnn_res.0.2", reduction = "wnn.umap")
```

```{r Extended Data Figure 4b}
# DimPlot of Subtype population with umap.rna
DimPlot(RGL_Astrocyte, group.by = "Subtype", reduction = "umap.rna",cols = RGL_Astrocyte_subtype_color)

# DimPlot of Subtype population with umap.atac
DimPlot(RGL_Astrocyte, group.by = "Subtype", reduction = "umap.atac", cols = RGL_Astrocyte_subtype_color)
```

```{r Extended Data Figure 4c}
#FeaturePlot of gene expression
DefaultAssay(RGL_Astrocyte) <- "RNA"
FeaturePlot(RGL_Astrocyte, reduction = "wnn.umap", features = c("FABP7","ALDH1L1","CD44","NRXN3","SLC1A2","LGR6") )
```

```{r Extended Data Figure 4d}
#RidgePlot of gene expression
RidgePlot(RGL_Astrocyte, group.by="Subtype", features=c("SOX2","GLIS3","FABP7","ALDH1L1","ALDH1A1","GFAP","CD44","DPP10","NRXN3","ROBO2","SLC1A2","LGR6","SEMA3E","MOBP"), 
          fill.by = "ident",
          col=RGL_Astrocyte_subtype_color,
          stack=T)
```

```{r Extended Data Figure 4e}
# subset different subtypes for next step
RGL_Astrocyte <-subset(RGL_Astrocyte, idents = c("Radial Glia", "CD-hi Astrocyte", "EAAT2-hi Astrocyte"))
# Transcription factor foorprinting
RGL_Astrocyte <- Footprint(
  object = RGL_Astrocyte,
  motif.name = c("RFX2","RFX3","RFX4","RORB","FOS"),
  genome = BSgenome.Hsapiens.UCSC.hg38)


# plot the footprint data for each Subtype
Idents(RGL_Astrocyte) <- "Subtype"

PlotFootprint(RGL_Astrocyte,features = c("RFX2","RFX3","RFX4","RORB","FOS")) & scale_color_manual(values = RGL_Astrocyte_subtype_color)

```

```{r Extended Data Figure 4f}
# subset CD44-hi Astrocyte for next step
CD44 <-subset(RGL_Astrocyte, idents = c("CD-hi Astrocyte"))
# Transcription factor foorprinting
CD44 <- Footprint(
  object = CD44,
  motif.name = c("FOS", "BACH2"),
  genome = BSgenome.Hsapiens.UCSC.hg38)

# plot the footprint data for each age group
Idents(CD44) <- "dev.group"

PlotFootprint(CD44,features = c("FOS", "BACH2")) & scale_color_manual(values = devcolor)
```







