---
title: "Extended Data Figure 1"
author: "Sheldon Ding"
date: "2026-05-06"
output: html_document
---

```{r load libraries}
#packages (some packages might require dependent packages)
library(Matrix)
library(Seurat)
library(Signac)
library(patchwork)
library(tidyverse)
library(dplyr)
library(readr)
library(magrittr)
library(harmony)
library(clustree)
library(GenomicRanges)
library(msigdbr)
library(clusterProfiler)
library(IRanges)
library(Biostrings)
library(biomaRt)
library(DESeq2)
library(DESeq2)
library(scCustomize)
library(openxlsx)
library(rGREAT)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ComplexHeatmap)
library(circlize)
```

```{r set seed}
set.seed(6)
```

```{r load object}
sobj <- readRDS("output/objects/atlas.RDS")
preqc <- readRDS("output/objects/preqc.RDS")
```

```{r color}
cellcolor <- c("Ependymal" = "#000000","Radial Glia" =  "#fcff5d", "Astrocyte" = "orange","Intermediate Proliferative Cell" = "#DFFF00","PAX6+ NEUROD1+ Neuroblast" = "#7dfc00", "Neuron" ="#0B6623", "PAX6+ HOXB3+ Neuroblast" = "#66CDAA", "Neuronal Progenitor" = "#808000","Fetal COP" = "#00FFFF", "OPC" = "#42A5F5", "COP" = "#0D47A1","Early OL" = "#000080","OL" = "#37294f", "Endothelial" = "#C2A57B","Pericyte" = "#6E260E","Mesenchymal" = "#b732cc","Lymphocyte" = "#FF9AA2", "Myeloid" = "#FF1493","Erythroblast" = "#C94C4C")
```


###Extended Data Figure 1
```{r Extended Data Figure 1a}
postqc <- subset(preqc,
               subset = 
                 TSS.enrichment > 1.5 &
                 nucleosome_signal < 2.5 &
                 blacklist_ratio < 0.05 &
                 nFeature_ATAC < 30000 &
                 nCount_ATAC < 80000 &
                 nFeature_RNA < 5000 &
                 nCount_RNA < 30000 &
                 percent.mt < 20 &
                 Predicted_Doublets == "Singlet")
postmeta <- postqc@meta.data
premeta <- preqc@meta.data

DensityScatter(preqc, x = 'nCount_RNA', y = 'percent.mt', log_x = TRUE, quantiles = TRUE)  %>% 
  ggsave(filename = "results/preqc_nCt_MT_dens.pdf", height = 5,width =6)

DensityScatter(postqc, x = 'nCount_RNA', y = 'percent.mt', log_x = TRUE, quantiles = TRUE)  %>% 
  ggsave(filename = "results/postqc_nCt_MT_dens.pdf", height = 5,width =6)

DensityScatter(preqc, x = 'nCount_ATAC', y = 'nucleosome_signal', log_x = TRUE, quantiles = TRUE)  %>% 
  ggsave(filename = "results/preqc_nCt_NS_dens.pdf", height = 5,width =6)

DensityScatter(postqc, x = 'nCount_ATAC', y = 'nucleosome_signal', log_x = TRUE, quantiles = TRUE)  %>% 
  ggsave(filename = "results/postqc_nCt_NS_dens.pdf", height = 5,width =6)
```


```{r Extended Data Figure 1b}
tbl.list<-list(table(premeta$TSS.enrichment > 1.5),
table(premeta$nucleosome_signal < 2.5),
table(premeta$blacklist_ratio < 0.05),
table(premeta$nFeature_ATAC < 30000),
table(premeta$nCount_ATAC < 80000),
table(premeta$nFeature_RNA < 5000),
table(premeta$nCount_RNA < 30000),
table(premeta$percent.mt < 20),
table(premeta$Predicted_Doublets == "Singlet"))
names(tbl.list) <- c("TSS.enrichment","Nucleosome_signal","Blacklist_ratio",
                     "nFeature_ATAC","nCount_ATAC","nFeature_RNA","nCount_RNA",
                     "Percent_mt","Predicted_doublets")

tbl.df <- data.frame(tbl.list[[1]])
tbl.df$metric <- names(tbl.list)[[1]]
for (i in 2:length(tbl.list)) {
  tbl <- data.frame(tbl.list[[i]])
  tbl$metric <- names(tbl.list)[[i]]
  tbl.df <- rbind(tbl.df,tbl)
}

tbl.df<-tbl.df[tbl.df$Var1 != TRUE,]
total_cells <- dim(premeta)[1]
tbl.df$percent_cells <- round((tbl.df$Freq /total_cells )*100,digits=2) %>% 
  paste0(.,"%")
tbl.df$Var1 <- NULL
tbl.df<-tbl.df[c(2,1,3)]



write.xlsx(tbl.df,"results/QC_cutoff.xlsx")


```


```{r Extended Data Figure 1c}
# DimPlot of resolution of SCT_res.0.8 with umap.rna
DimPlot(sobj, group.by = "SCT_res.0.8", reduction = "umap.rna")

# DimPlot of resolution of ATAC_res.0.2 with umap.atac
DimPlot(sobj, group.by = "ATAC_res.0.2", reduction = "umap.atac")

# DimPlot of resolution of wsnn_res.0.2 with wnn.umap
DimPlot(sobj, group.by = "wsnn_res.0.2", reduction = "wnn.umap")
```

```{r Extended Data Figure 1d}
marker.gene <- c("FOXJ1","PIFO","DNAH7","SOX2","YAP1","FABP7","TNC","CENPF","TOP2A","PAX3","PAX6","HOXB3","DCX","MAP2","TUBB3","STMN2","RBFOX3","AQP4","ALDH1L1","PDGFRA","OLIG2","BCAS1","SOX10","PLP1","TCF7L2","MYRF","MBP","CNP","MOBP","LUM","PTPRC","P2RY12","PECAM1","SLC4A1","GYPA","PDGFRB")
VlnPlot(sobj, features = marker.gene, 
          group.by = "Cell_Type", stack = T, fill.by = "ident", flip = T, cols = cellcolor) + scale_y_discrete(limits=rev)
```

```{r Extended Data Figure 1e}

clust_11_subcluster <-subset(sobj,  "wsnn_res.0.2" == 11)

#run harmony to remove batch effect again on RNA assay
clust_11_harmony <- clust_11_subcluster#create a separate object in case mess up something
DefaultAssay(clust_11_harmony) <- "RNA"
clust_11_harmony <- clust_11_harmony %>% NormalizeData() %>%FindVariableFeatures(selection.method = "vst", nfeatures=3000) %>%   ScaleData() %>%SCTransform(vars.to.regress = NULL)
clust_11_harmony <- RunPCA(clust_11_harmony, assay = "SCT", npcs = 50)
clust_11_harmony <- RunHarmony(clust_11_harmony,group.by.vars = c("sample_id"),reduction = "pca", assay.use = "SCT", reduction.save = "rna_harmony")

clust_11_harmony <- clust_11_harmony  %>%
  RunUMAP(reduction = "rna_harmony", assay = "SCT", dims = 1:50, reduction.name = 'umap.rna', reduction.key = 'rnaUMAP_') %>%
  FindNeighbors(reduction = "rna_harmony") %>%
  FindClusters(resolution = c(0.2, 0.4, 0.6, 0.8, 1.0, 1.2), verbose = TRUE)


DefaultAssay(clust_11_harmony) <- "ATAC" 
clust_11_harmony <- RunTFIDF(clust_11_harmony) 
clust_11_harmony <- FindTopFeatures(clust_11_harmony, min.cutoff = 'q0') 
clust_11_harmony <- RunSVD(clust_11_harmony) 
clust_11_harmony <- RunUMAP(clust_11_harmony, dims = 2:50, reduction = 'lsi')
clust_11_harmony <- RunHarmony(object = clust_11_harmony, group.by.vars = c('sample_id'),reduction = 'lsi', assay.use = 'ATAC', project.dim = FALSE,  reduction.save = "atac_harmony")
clust_11_harmony <- RunUMAP(clust_11_harmony, dims = 2:50, reduction = 'atac_harmony', reduction.name = 'umap.atac', reduction.key = 'atacUMAP_')

clust_11_harmony <- FindMultiModalNeighbors(clust_11_harmony, reduction.list = list("rna_harmony", "atac_harmony"), dims.list = list(1:50, 2:50))
clust_11_harmony <- RunUMAP(clust_11_harmony, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
clust_11_harmony <- FindClusters(clust_11_harmony, graph.name = "wsnn", algorithm = 3, verbose = FALSE,
                                 resolution = c(0.2, 0.4, 0.6, 0.8, 1.0, 1.2))

clust_11_harmony$Cell_Type<-case_when(clust_11_harmony$wsnn_res.0.2 == 3 ~ "Lymphocyte",
          (clust_11_harmony$wsnn_res.0.2 == 2) ~ "Postnatal Glial Progenitor", 
           (clust_11_harmony$wsnn_res.0.2 != 2) & (clust_11_harmony$postnatal != "Postnatal")  ~ "Fetal Neuronal Progenitor")


DimPlot(clust_11_harmony, group.by = "wsnn_res.0.2")

DimPlot(clust_11_harmony, group.by = "postnatal")

DimPlot(clust_11_harmony, group.by = "Cell_Type", cols = cellcolor)
```

```{r Extended Data Figure 1f}
FeaturePlot(clust_11_harmony, features=c("STMN2","TUBB3","GFAP","MOBP","CD3D","PTPRC"),coord.fixed = T)
```



















