---
title: "Figure 4"
author: "Sheldon Ding"
date: "2026-05-05"
output: html_document
---

```{r load libraries}
#packages (some packages might require dependent packages)
library(Matrix)
library(Seurat)
library(Signac)
library(patchwork)
library(tidyverse)
library(dplyr)
library(readr)
library(magrittr)
library(harmony)
library(clustree)
library(GenomicRanges)
library(msigdbr)
library(clusterProfiler)
library(IRanges)
library(Biostrings)
library(biomaRt)
library(DESeq2)
library(DESeq2)
library(scCustomize)
library(openxlsx)
library(rGREAT)
library(BSgenome.Hsapiens.UCSC.hg38)
library(ComplexHeatmap)
library(circlize)
library(monocle3)
```

```{r set seed}
set.seed(6)
```

```{r load object}
sobj <- readRDS("output/objects/atlas.RDS")
```

```{r color}
devcolor <- c("Fetal" = "#0D0887", "Infant" = "#7E03A8", "Child" ="#CC4678","Adolescent" = "#F89441","Adult" = "#F0F921")

OL_subtype_colors <-  c("Early OL" = "#3998f5","RBFOX1 OL" = "#8A2BE2","OPALIN OL" = "#1A3EAB")
```


###Figure 4
```{r}
Idents(sobj) <- "Cell_Type"

# subset out "Early OL", "OL" for downstream analysis
OL <-subset(sobj, idents = c("Early OL", "OL"))

# run harmony to remove batch effect again on RNA assay
DefaultAssay(OL) <- "RNA"
OL <- OL %>% NormalizeData() %>%FindVariableFeatures(selection.method = "vst", nfeatures=3000) %>%   ScaleData() %>%SCTransform(vars.to.regress = NULL)
OL <- RunPCA(OL, assay = "SCT", npcs = 50)
OL <- RunHarmony(OL,group.by.vars = c("sample_id"),reduction = "pca", assay.use = "SCT", reduction.save = "rna")

# normalize and SCT transform again after harmony
DefaultAssay(OL) <- "RNA"
OL <- OL %>%
  NormalizeData() %>%
  FindVariableFeatures(selection.method = "vst", nfeatures=3000) %>%
  ScaleData() %>%
  SCTransform(vars.to.regress = NULL)

# recluster OL subset
OL <- OL  %>%
  RunUMAP(reduction = "rna", assay = "SCT", dims = 1:50, reduction.name = 'umap.rna', reduction.key = 'rnaUMAP_') %>%
  FindNeighbors(reduction = "rna") %>%
  FindClusters(verbose = TRUE)

# run harmony to remove batch effect again on ATAC assay
DefaultAssay(OL) <- "ATAC" 
OL <- RunTFIDF(OL) 
OL <- FindTopFeatures(OL, min.cutoff = 'q0') 
OL <- RunSVD(OL) 
OL <- RunUMAP(OL, dims = 2:50, reduction = 'lsi')
OL <- RunHarmony(object = OL, group.by.vars = c('sample_id'),reduction = 'lsi', assay.use = 'ATAC', project.dim = FALSE,  reduction.save = "atac")
OL <- RunUMAP(OL, dims = 2:50, reduction = 'atac', reduction.name = 'umap.atac', reduction.key = 'atacUMAP_')

# run wnn on harmonized RNA and ATAC reduction
OL <- FindMultiModalNeighbors(OL, reduction.list = list("rna", "atac"), dims.list = list(1:50, 2:50))
OL <- RunUMAP(OL, nn.name = "weighted.nn", reduction.name = "wnn.umap", reduction.key = "wnnUMAP_")
OL <- FindClusters(OL, graph.name = "wsnn", algorithm = 3, verbose = FALSE)

# set wnn resolution @ 0.2 for downstream analysis
Idents(OL) <- "wsnn_res.0.2"

# based on DAP, DEG and canonical marker, we determined subtype of each cluster

# set cluster identity to Subtype
new_names <- c(
  "0" = "RBFOX1 OL",
  "1" = "RBFOX1 OL",
  "2" = "OPALIN OL",
  "3" = "Early OL",
  "4" = "OPALIN OL",
  "5" = "Early OL",
  "6" = "OPALIN OL",
  "7" = "RBFOX1 OL",
  "8" = "RBFOX1 OL",
  "9" = "RBFOX1 OL",
  "10" = "RBFOX1 OL",
  "11" = "RBFOX1 OL",
  "12" = "RBFOX1 OL",
  "13" = "OPALIN OL",
  "14" = "RBFOX1 OL",
  "15" = "RBFOX1 OL",
  "16" = "RBFOX1 OL",
  "17" = "RBFOX1 OL",
  "18" = "RBFOX1 OL",
  "19" = "RBFOX1 OL",
  "20" = "RBFOX1 OL",
  "21" = "OPALIN OL",
  "22" = "OPALIN OL",
  "23" = "RBFOX1 OL",
  "24" = "RBFOX1 OL",
  "25" = "RBFOX1 OL",
  "26" = "RBFOX1 OL",
  "27" = "RBFOX1 OL",
  "28" = "RBFOX1 OL",
  "29" = "RBFOX1 OL",
  "30" = "OPALIN OL",
  "31" = "RBFOX1 OL"
)

OL <- RenameIdents(OL, new_names)

OL@active.ident <- factor(x = OL@active.ident, levels = c("Early OL", "RBFOX1 OL", "OPALIN OL"))
# add metadata of Subtype
OL$Subtype <- OL@active.ident

# DimPlot using wnn.umap group by Subtype
DimPlot(OL, reduction = "wnn.umap", group.by = "Subtype",cols = OL_subtype_colors)
```

```{r Figure 4b}
# DimPlot using wnn.map group by dev.group
DimPlot(OL, group.by = "dev.group",reduction = "wnn.umap", cols = devcolor)
```

```{r Figure 4c}
# extract metadata of dev.group and Subtype for ggplot visualization
OL@meta.data %>% group_by(Subtype, dev.group) %>% summarise(n = n()) %>% group_by(dev.group) %>% mutate(freq = n / sum(n)) %>% data.frame -> df1

# plot subtype composition difference across ages on BarPlot
ggplot(df1, aes(x = dev.group, y = freq, fill = Subtype)) +
  geom_bar(stat = "identity", width = 0.9) +
  xlab("dev.group") + ylab("Proportion")+
  scale_fill_manual(values = OL_subtype_colors) +
  theme_classic()+ scale_y_continuous(expand = c(0, 0))+
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1)
  )
```

```{r Figure 4d}
# transform the seurat object into a cds object for monocle to work
DefaultAssay(OL) <- "RNA"
cds <- as.cell_data_set(OL)
colData(cds)
fData(cds)
rownames(fData(cds))[1:10]
fData(cds)$gene_short_name<-rownames(fData(cds))
counts(cds)

# create the umap partition and cell embeddings including seurat metadata on cds object
reacreate.partition<-c(rep(1,length(cds@colData@rownames)))
reacreate.partition
names(reacreate.partition)<-cds@colData@rownames
reacreate.partition<-as.factor(reacreate.partition)
reacreate.partition
cds@clusters$UMAP$partitions<-reacreate.partition
list_cluster<-OL@active.ident
cds@clusters$UMAP$clusters<-list_cluster
cds@int_colData@listData$reducedDims$UMAP<-OL@reductions$wnn.umap@cell.embeddings

# "learn graph" in order to calculate cell trajectory and pseudotime
cds<-learn_graph(cds,use_partition = TRUE)

# plot pseudotime on DimPlot with wnn.umap
Cell_pseudotime <- plot_cells(cds,
           color_cells_by = "pseudotime",
           group_cells_by = "ident",
           label_cell_groups = FALSE,
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           label_roots = FALSE,
           show_trajectory_graph = TRUE) +
  scale_color_gradientn(
    colors = c("#2c7bb6", "#abd9e9", "#ffffbf", "#fdae61", "#d7191c")
  )
```

```{r Figure 4e}
DefaultAssay(OL) <- "RNA"

# gene expression on feature plot
FeaturePlot(OL, features = c("NKX6-2","OPALIN","NLGN1","RBFOX1","S100A1"), reduction = "wnn.umap")
```

```{r Figure 4f}
DefaultAssay(OL) <- "RNA"
Idents(OL) <- "Subtype"

# calculate the DEG between OPALIN OL and RBFIX1 OL
agg<-AggregateExpression(OL,assays="RNA", return.seurat=F, group.by=c("sample_id","Subtype"))
pb <- agg$RNA
colnames(pb)<- gsub("-","_",colnames(pb))
meta <- OL@meta.data[, c("Subtype","sample_id","dev.group","Sex","Race","postnatal")]

meta_unique <- meta[!duplicated(paste(meta$sample_id, meta$Subtype)), ]

meta_unique$colname <- paste(meta_unique$sample_id,
                             meta_unique$Subtype,
                             sep = "_") %>% gsub("-","_",.)
rownames(meta_unique) <- meta_unique$colname
rownames(meta_unique)[grep("10X",rownames(meta_unique))] <- paste0("g",rownames(meta_unique)[grep("10X",rownames(meta_unique))])
meta_unique <- meta_unique[colnames(pb), ]

cellcount<-table(OL$Subtype,OL$sample_id) %>% data.frame()
rownames(cellcount)<-paste(cellcount$Var2,cellcount$Var1,sep="_")
rownames(cellcount)[grep("10X", rownames(cellcount))] <- paste0("g",rownames(cellcount)[grep("10X", rownames(cellcount))]) 


meta_unique$CellCount<-cellcount[rownames(meta_unique),]$Freq

#check
all(rownames(meta_unique) == colnames(pb))

ct.1 <- "OPALIN OL"
ct.2 <- "RBFOX1 OL"
keep <- (meta_unique$Subtype == ct.1 | meta_unique$Subtype == ct.2)

ct_counts <- pb[, keep]
ct_meta   <- meta_unique[keep, ]

ct_meta$dev.group <- factor(ct_meta$dev.group,
                            levels = c("Infant","Child","Adolescent","Adult"))
ct_meta$Sex[is.na(ct_meta$Sex)] <- "NAFetal"
ct_meta$Sex <- factor(ct_meta$Sex)
ct_meta$Subtype <- factor(ct_meta$Subtype, levels = c(ct.2, ct.1))
dds <- DESeqDataSetFromMatrix(
  countData = round(ct_counts),
  colData = ct_meta,
  design = ~ Subtype + dev.group
)

keep_genes <- rowSums(counts(dds)) >= 10
dds <- dds[keep_genes, ]

dds <- DESeq(dds)
vsd <- vst(dds)

res <- results(dds, name="Subtype_OPALIN.OL_vs_RBFOX1.OL")
res <- lfcShrink(dds,
                 coef="Subtype_OPALIN.OL_vs_RBFOX1.OL",
                 res=res, type = "normal")
res.df<-res %>% data.frame


res_tbl <- res %>%
  data.frame() %>%
  rownames_to_column(var="gene") %>%
  as_tibble()

# set thresholds
padj_cutoff <- 0.05
res_table_thres <- res_tbl %>% 
  mutate(threshold = padj < 0.05 & abs(log2FoldChange) >= 1)

# set comparison direction
res_table_thres$direction <- ""
res_table_thres$direction[!is.na(sign(res_table_thres$log2FoldChange))] <- ifelse(sign(res_table_thres$log2FoldChange[!is.na(sign(res_table_thres$log2FoldChange))])==-1, yes = "down", no = "up")
res_table_thres$threshold[is.na(res_table_thres$threshold)]<-FALSE

Top_Hits <- head(arrange(res_table_thres, padj), 10)
Top_Hits <- rbind(Top_Hits, head(arrange(res_table_thres[res_table_thres$log2FoldChange >=1,], desc(log2FoldChange)), 5))

# Create the 'label' column: gene name for top hits, NULL otherwise
res_table_thres$label <- if_else(res_table_thres$gene %in% Top_Hits$gene, res_table_thres$gene, as.character(NA))

# top hits DEG beteen RBFOX1 OL and OPALIN OL volcano plot
ggplot(data=res_table_thres, aes(x=log2FoldChange, y=-1*log10(padj), color=threshold)) +geom_point(size=1) + scale_color_manual(values= c("black","red3")) + geom_vline(xintercept = 1,linetype = "dashed")+geom_vline(xintercept = -1,linetype = "dashed")+geom_hline(yintercept = -1*log10(0.05),linetype = "dashed")+theme_bw() + ggrepel::geom_text_repel(
  aes(label = label),
  size = 3,        
  box.padding = 0.5,
  point.padding = 0.5,
  segment.color = 'grey50', 
  show.legend = FALSE,
  color="black"
)
```

```{r Figure 4g}
DEA <- unique(meta_unique$Subtype)

res_list <- list()
for(cell in gsub(" ",".",gsub("\\+",".",DEA))){
  message(cell)
  res <- results(dds, name=paste0("Subtype",cell))
  res.df <- data.frame(res)
  res.df$gene <- rownames(res.df)
  res.df<-subset(res.df, log2FoldChange > 0)
  res.df<-res.df[order(res.df$padj, decreasing = F),]
  if(length(res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1.5]) > 0) {
    res.df$pct.expressed<- NA
    res.df$pct.expressed[res.df$gene %in% res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1.5]] <- scCustomize::Percent_Expressing(OL_lineage, features = res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1.5], assay="RNA",group.by="Subtype")[,cell]
  }
  res_list[[cell]] <- res.df
}

# Load the genesets
ensembl = useMart("ensembl", dataset = "hsapiens_gene_ensembl")

# For C5 gene ontology genesets
C5genesets <- msigdbr(species = "Homo sapiens", category = "C5")
C5togene <- C5genesets[,c("gs_exact_source","gene_symbol")]
C5toname <- C5genesets[,c("gs_exact_source","gs_name")]

# For GO Biological Process
GOgenesets <- subset(C5genesets, subset=C5genesets[,"gs_subcat"]=="GO:BP")
GOtogene <- GOgenesets[,c("gs_exact_source","gene_symbol")]
GOtoname <- GOgenesets[,c("gs_exact_source","gs_name")]

list <- c("OPALIN.OL","RBFOX1.OL")

# get the GO Biological Process
GO <- lapply(list, function (x)
{
  print(x)
  y <- enricher(gene = res_list[[x]]$gene[res_list[[x]]$log2FoldChange > 1.5 &  res_list[[x]]$padj < 0.05 &  res_list[[x]]$pct.expressed > 10],
                pvalueCutoff = 0.05,
                pAdjustMethod = "BH",
                minGSSize = 15,
                maxGSSize = 1000,
                qvalueCutoff = 0.2,
                TERM2GENE = GOtogene,
                TERM2NAME = GOtoname)
})

names(GO) <- list

# plot the top 5 GO Biological Process in OPALIN OL on DotPlot
p_OPALIN <- dotplot(
  GO[["OPALIN.OL"]],
  x = "GeneRatio",
  color = "p.adjust",
  showCategory = 5
)
```

```{r}
# plot the top 5 GO Biological Process in RBFOX1 OL on DotPlot
p_RBFOX1 <- dotplot(
  GO[["RBFOX1.OL"]],
  x = "GeneRatio",
  color = "p.adjust",
  showCategory = 5
)
```

```{r Figure 4i}
# IF staining microscopy images
```

```{r Figure 4j}
# IF staining microscopy images
```

```{r Figure 4k left}
OPALIN <- subset(OL, Subtype == "OPALIN OL" & dev.group != "Fetal")
DefaultAssay(OPALIN) <- "RNA"
Idents(OPALIN) <- "dev.group"

# to calculate DEG between different age groups in postnatal OPALIN OL using DESeq2
agg<-AggregateExpression(OPALIN,assays="RNA", return.seurat=F, group.by=c("sample_id","dev.group"))
pb <- agg$RNA
colnames(pb)<- gsub("-","_",colnames(pb))
meta <- OPALIN@meta.data[, c("dev.group","sample_id","Sex","Race","postnatal")]

meta_unique <- meta[!duplicated(paste(meta$sample_id, meta$dev.group)), ]

meta_unique$colname <- paste(meta_unique$sample_id,
                             meta_unique$dev.group,
                             sep = "_") %>% gsub("-","_",.)
rownames(meta_unique) <- meta_unique$colname
rownames(meta_unique)[grep("10X",rownames(meta_unique))] <- paste0("g",rownames(meta_unique)[grep("10X",rownames(meta_unique))])
meta_unique <- meta_unique[colnames(pb), ]


cellcount<-table(OPALIN$dev.group,OPALIN$sample_id) %>% data.frame()
rownames(cellcount)<-paste(cellcount$Var2,cellcount$Var1,sep="_")
rownames(cellcount)[grep("10X", rownames(cellcount))] <- paste0("g",rownames(cellcount)[grep("10X", rownames(cellcount))]) 



meta_unique$CellCount<-cellcount[rownames(meta_unique),]$Freq

# check
all(rownames(meta_unique) == colnames(pb))

DEA <- unique(meta_unique$dev.group)


ct_counts <- pb
ct_meta   <- meta_unique

ct_meta$dev.group <- factor(ct_meta$dev.group,
                            levels = c("Infant","Child","Adolescent","Adult"))
ct_meta$Sex[is.na(ct_meta$Sex)] <- "NAFetal"
ct_meta$Sex <- factor(ct_meta$Sex)
dds <- DESeqDataSetFromMatrix(
  countData = round(ct_counts),
  colData = ct_meta,
  design = ~ dev.group
)

keep_genes <- rowSums(counts(dds)) >= 10
dds <- dds[keep_genes, ]

dds <- DESeq(dds,betaPrior=TRUE)
vsd <- vst(dds)

res_list_ct <- list()
for(cell in gsub(" ",".",gsub("\\+",".",DEA))){
  message(cell)
  res <- results(dds, name=paste0("dev.group",cell))
  res.df <- data.frame(res)
  res.df$gene <- rownames(res.df)
  res.df<-subset(res.df, log2FoldChange > 0)
  res.df<-res.df[order(res.df$padj, decreasing = F),]
  if(length(res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1]) > 0) {
    res.df$pct.expressed<- NA
    res.df$pct.expressed[res.df$gene %in% res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1]] <- scCustomize::Percent_Expressing(OPALIN, features = res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1], assay="RNA",group.by="dev.group")[,cell]
  }
  res_list_ct[[cell]] <- res.df
}

# write DEG
write.xlsx(res_list_ct, "/output/OPALIN_DEG.xlsx")

# read in DEG
sheetnames <- excel_sheets("/output/OPALIN_Age_DEG.xlsx")
degs<-lapply(sheetnames, function(sheet) {
  read_xlsx("/output/OPALIN_Age_DEG.xlsx", sheet=sheet)
})
names(degs) <- sheetnames

top_degs <- list()
for(cell in sheetnames){
  res.df <- degs[[cell]]
  print(cell)
  top_degs[[cell]] <- res.df$gene[res.df$padj < 0.05 & res.df$log2FoldChange > 1 & !is.na(res.df$padj) & res.df$pct.expressed > 5]
  
}
top_degs_unique<-c(top_degs$Infant, top_degs$Child,top_degs$Adolescent, top_degs$Adult) %>% unique()

top.mat<-GetAssayData(OPALIN, assay="RNA")
top.mat<-top.mat[c(top_degs_unique),] %>% as.matrix

colData <- data.frame(dev.group = factor(OPALIN$dev.group[colnames(top.mat)], levels=names(devcolor)[2:5]), sample_id = OPALIN$sample_id) 

top.mat <- top.mat[,order(colData$dev.group)]
colData <- colData[order(colData$dev.group),]

col_ha <- HeatmapAnnotation(
  dev_group = colData$dev.group,
  col = list(dev_group = devcolor[2:5])
)

jet.colors <- colorRamp2::colorRamp2(
  c(0, 2, 5),
  hcl_palette = "Reds",
  reverse=T
)


jet.colors <- colorRamp2::colorRamp2(
  seq(-2, 6, length.out = 5),
  c("blue", "lightblue", "yellow", "orange", "red")
)

# plot top DEG in each age group of OPALIN OL on heatmap
Heatmap(
  t(scale(t(as.matrix(top.mat)))),
  name = "Expression",
  top_annotation = col_ha,
  show_row_names = T,
  show_column_names = FALSE,
  cluster_columns = F,
  cluster_rows = F,
  col = jet.colors
)
```

```{r Figure 4k right}
RBFOX1 <- subset(OL, Subtype == "RBFOX1 OL" & dev.group != "Fetal")
DefaultAssay(RBFOX1) <- "RNA"
Idents(RBFOX1) <- "dev.group"

# calculate DEG between different age groups in postnatal RBFOX1 OL using DESeq2
agg<-AggregateExpression(RBFOX1,assays="RNA", return.seurat=F, group.by=c("sample_id","dev.group"))
pb <- agg$RNA
colnames(pb)<- gsub("-","_",colnames(pb))
meta <- RBFOX1@meta.data[, c("dev.group","sample_id","Sex","Race","postnatal")]

meta_unique <- meta[!duplicated(paste(meta$sample_id, meta$dev.group)), ]

meta_unique$colname <- paste(meta_unique$sample_id,
                             meta_unique$dev.group,
                             sep = "_") %>% gsub("-","_",.)
rownames(meta_unique) <- meta_unique$colname
rownames(meta_unique)[grep("10X",rownames(meta_unique))] <- paste0("g",rownames(meta_unique)[grep("10X",rownames(meta_unique))])
meta_unique <- meta_unique[colnames(pb), ]


cellcount<-table(RBFOX1$dev.group,RBFOX1$sample_id) %>% data.frame()
rownames(cellcount)<-paste(cellcount$Var2,cellcount$Var1,sep="_")
rownames(cellcount)[grep("10X", rownames(cellcount))] <- paste0("g",rownames(cellcount)[grep("10X", rownames(cellcount))]) 



meta_unique$CellCount<-cellcount[rownames(meta_unique),]$Freq

#check
all(rownames(meta_unique) == colnames(pb))

DEA <- unique(meta_unique$dev.group)


ct_counts <- pb
ct_meta   <- meta_unique

ct_meta$dev.group <- factor(ct_meta$dev.group,
                            levels = c("Infant","Child","Adolescent","Adult"))
ct_meta$Sex[is.na(ct_meta$Sex)] <- "NAFetal"
ct_meta$Sex <- factor(ct_meta$Sex)
dds <- DESeqDataSetFromMatrix(
  countData = round(ct_counts),
  colData = ct_meta,
  design = ~ dev.group
)

keep_genes <- rowSums(counts(dds)) >= 10
dds <- dds[keep_genes, ]

dds <- DESeq(dds,betaPrior=TRUE)
vsd <- vst(dds)

res_list_ct <- list()
for(cell in gsub(" ",".",gsub("\\+",".",DEA))){
  message(cell)
  res <- results(dds, name=paste0("dev.group",cell))
  res.df <- data.frame(res)
  res.df$gene <- rownames(res.df)
  res.df<-subset(res.df, log2FoldChange > 0)
  res.df<-res.df[order(res.df$padj, decreasing = F),]
  if(length(res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1]) > 0) {
    res.df$pct.expressed<- NA
    res.df$pct.expressed[res.df$gene %in% res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1]] <- scCustomize::Percent_Expressing(RBFOX1, features = res.df$gene[complete.cases(res.df[, c("padj", "log2FoldChange")]) &res.df$padj < 0.05 & res.df$log2FoldChange > 1], assay="RNA",group.by="dev.group")[,cell]
  }
  res_list_ct[[cell]] <- res.df
}

# write DEG
write.xlsx(res_list_ct, "/output/RBFOX1_DEG.xlsx")

# read in DEG
sheetnames <- excel_sheets("/output/RBFOX1_Age_DEG.xlsx")
degs<-lapply(sheetnames, function(sheet) {
  read_xlsx("/output/RBFOX1_Age_DEG.xlsx", sheet=sheet)
})
names(degs) <- sheetnames

top_degs <- list()
for(cell in sheetnames){
  res.df <- degs[[cell]]
  print(cell)
  top_degs[[cell]] <- res.df$gene[res.df$padj < 0.05 & res.df$log2FoldChange > 1 & !is.na(res.df$padj) & res.df$pct.expressed > 5]
  
}
top_degs_unique<-c(top_degs$Infant, top_degs$Child,top_degs$Adolescent, top_degs$Adult) %>% unique()

top.mat<-GetAssayData(RBFOX1, assay="RNA")
top.mat<-top.mat[c(top_degs_unique),] %>% as.matrix

colData <- data.frame(dev.group = factor(RBFOX1$dev.group[colnames(top.mat)], levels=names(devcolor)[2:5]), sample_id = RBFOX1$sample_id) 

top.mat <- top.mat[,order(colData$dev.group)]
colData <- colData[order(colData$dev.group),]

col_ha <- HeatmapAnnotation(
  dev_group = colData$dev.group,
  col = list(dev_group = devcolor[2:5])
)

jet.colors <- colorRamp2::colorRamp2(
  c(0, 2, 5),
  hcl_palette = "Reds",
  reverse=T
)


jet.colors <- colorRamp2::colorRamp2(
  seq(-2, 6, length.out = 5),
  c("blue", "lightblue", "yellow", "orange", "red")
)

# plot top DEG in each age group of RBFOX1 OL on heatmap
Heatmap(
  t(scale(t(as.matrix(top.mat)))),
  name = "Expression",
  top_annotation = col_ha,
  show_row_names = T,
  show_column_names = FALSE,
  cluster_columns = F,
  cluster_rows = F,
  col = jet.colors
)
```

```{r save RDS object}
saveRDS(OL, "/output/objects/OL.RDS")
```










