---
title: "Supplemental_Figuer_2_Analysis"
author: "Sheldon Ding"
date: "2025-03-21"
output: html_document
---

```{r load libraries}
#packages (some packages might require dependent packages)
library(Matrix)
library(Seurat)
library(Signac)
library(patchwork)
library(tidyverse)
library(dplyr)
library(readr)
library(magrittr)
library(openxlsx) 
library(harmony)
library(clustree)
library(rGREAT)
library(GenomicRanges)
library(msigdbr)
library(clusterProfiler)
library(AnnotationHub)
library(TFBSTools)
library(BSgenome.Hsapiens.UCSC.hg38)
library(IRanges)
library(Biostrings)
library(openxlsx)
library(biomaRt)
library(DESeq2)
library(grid)
library(SeuratWrappers)
library(monocle3)
library(EnhancedVolcano)
```

```{r set seed}
set.seed(6)
```

```{r load object}
RGL_Astrocyte_harmony <- readRDS("/objects/RGL_Astrocyte_harmony.rds")
```

```{r set color for cell type and age}
#cell type
RGL_Astrocyte_subcluster_color = c("ROBO2 Radial Glia" = "#e2e700","SLIT2 Radial Glia" = "#FFDAB9", "ROBO2 Astrocyte" = "#FFA500","SEMA3E Astrocyte" = "#FF4F00","OL-like Astrocyte" = "#C2A162","Undetermined Astrocyte" = "#BDC3C7")

#age
devcolor <- c("Fetal" =  "#0D0887", "Infant" = "#7E03A8", "Child" ="#CC4678","Adolescent" = "#F89441","Adult" = "#F0F921")
```


###Supplemental Figure 2
```{r Supplemental Figure 2A}
#set active identity to SCT_snn_res.0.6
RGL_Astrocyte_harmony <- SetIdent(RGL_Astrocyte_harmony, value = RGL_Astrocyte_harmony@meta.data$SCT_snn_res.0.6)

##to plot cluster on RNA DimPlot
DimPlot(RGL_Astrocyte_harmony, label = F, reduction = "umap.rna", label = T) + NoLegend()
```

```{r Supplemental Figure 2B}
#set active identity to subcluster
RGL_Astrocyte_harmony <- SetIdent(RGL_Astrocyte_harmony, value = RGL_Astrocyte_harmony@meta.data$Subcluster)

##to plot subcluster on ATAC DimPlot
DimPlot(RGL_Astrocyte_harmony, label = F, reduction = "umap.rna", label = F)
```

```{r Supplemental Figure 2C}
##to plot markers differentiating assigned subclusters on FeaturePlot
DefaultAssay(RGL_Astrocyte_harmony) <- "RNA"
FeaturePlot(RGL_Astrocyte_harmony, features = c("SOX2", "FABP7","GRIN2A","AQP1","GFAP","ALDH1L1","ROBO2","SLIT2", "SEMA3E"), keep.scale = "all")
```

```{r Supplemental Figure 2D}
##calculate the DAP in each subcluster
DefaultAssay(RGL_Astrocyte_harmony) <- "ATAC"
RGL_Astrocyte_harmony <- SetIdent(RGL_Astrocyte_harmony, value = RGL_Astrocyte_harmony@meta.data$Subcluster)
RGL_Astrocyte_harmony_subcluster_DAP <- FindAllMarkers(RGL_Astrocyte_harmony, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

#extract the DAP in each subcluster and make a list
RGL_Astrocyte_Subcluster_DAP_list <- list(ROBO2_Radial_Glia_DAP,SLIT2_Radial_Glia_DAP,ROBO2_Astrocyte_DAP,SEMA3E_Astrocyte_DAP,Oligo_like_Astrocyte_DAP)

#run the rGreat analysis
RGL_Astrocyte_Subcluster_DAP_list <- lapply(RGL_Astrocyte_Subcluster_DAP_list, function(x) { x <- x %>%
  separate(gene, into = c("seqnames", "start", "end"), sep = "-")
x$start <- as.numeric(x$start)
x$end <- as.numeric(x$end)
x$strand <- c("*")
return(x)})
g.RGL_Astrocyte_Subcluster_DAP_list <- lapply(RGL_Astrocyte_Subcluster_DAP_list, function(x) {x <- GenomicRanges::GRanges(
  seqnames = x$seqnames,
  ranges = IRanges(start = x$start,
                   end = x$end
  ),
  strand = x$strand,
  id = x$cluster,
  rank = x$avg_log2FC,
  adjust = x$p_val_adj)
return(x)})

#calculate the unique DAP in each subcluster
laps_Full <- findOverlapsOfPeaks(g.RGL_Astrocyte_Subcluster_DAP_list[[1]], g.RGL_Astrocyte_Subcluster_DAP_list[[2]], g.RGL_Astrocyte_Subcluster_DAP_list[[3]], g.RGL_Astrocyte_Subcluster_DAP_list[[4]], g.RGL_Astrocyte_Subcluster_DAP_list[[5]])

#visualize the unique DAP in each subcluster using VennDiagram
makeVennDiagram(laps_Full, NameOfPeaks = c("ROBO2 Radial Glia", "SLIT2 Radial Glia", "ROBO2 Astrocyte","SEMA3E Astrocyte","OL-like Astrocyte","Undetermined Astrocyte"), fill=c("ROBO2 Radial Glia" = "#e2e700","SLIT2 Radial Glia" = "#FFDAB9", "ROBO2 Astrocyte" = "#FFA500","SEMA3E Astrocyte" = "#FF4F00","OL-like Astrocyte" = "#C2A162","Undetermined Astrocyte" = "#BDC3C7"))
```

```{r Supplemental Figure 2E}
##calculate the DAP in each age group
DefaultAssay(RGL_Astrocyte_harmony) <- "ATAC"
RGL_Astrocyte_harmony <- SetIdent(RGL_Astrocyte_harmony, value = RGL_Astrocyte_harmony@meta.data$dev.group)
RGL_Astrocyte_harmony_age_DAP <- FindAllMarkers(RGL_Astrocyte_harmony, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)

#extract the DAP in each subcluster and make a list
RGL_Astrocyte_age_DAP_list <- list(Fetal_DAP, Infant_DAP, Child_DAP, Adolescent_DAP, Adult_DAP)

#run the rGreat analysis
RGL_Astrocyte_age_DAP_list <- lapply(RGL_Astrocyte_age_DAP_list, function(x) { x <- x %>%
  separate(gene, into = c("seqnames", "start", "end"), sep = "-")
x$start <- as.numeric(x$start)
x$end <- as.numeric(x$end)
x$strand <- c("*")
return(x)})
g.RGL_Astrocyte_age_DAP_list <- lapply(RGL_Astrocyte_age_DAP_list, function(x) {x <- GenomicRanges::GRanges(
  seqnames = x$seqnames,
  ranges = IRanges(start = x$start,
                   end = x$end
  ),
  strand = x$strand,
  id = x$cluster,
  rank = x$avg_log2FC,
  adjust = x$p_val_adj)
return(x)})

#calculate the unique DAP in each subcluster
laps_Full <- findOverlapsOfPeaks(g.RGL_Astrocyte_age_DAP_list[[1]], g.RGL_Astrocyte_age_DAP_list[[2]], g.RGL_Astrocyte_age_DAP_list[[3]], g.RGL_Astrocyte_age_DAP_list[[4]], g.RGL_Astrocyte_age_DAP_list[[5]])

#visualize the unique DAP in each subcluster using VennDiagram
makeVennDiagram(laps_Full, NameOfPeaks = c("Fetal", "Infant", "Child", "Adolescent", "Adult"), fill=c("Fetal" =  "#0D0887", "Infant" = "#7E03A8", "Child" ="#CC4678","Adolescent" = "#F89441","Adult" = "#F0F921"))
```

```{r Supplemental Figure 2F}
#rGreat analysis for computing the differenet pathway based on DAP
r.RGL_Astrocyte_age_DAP_list <- rGREAT::great(g.RGL_Astrocyte_age_DAP_list,
                        gene_sets = "msigdb:C5:GO:BP",
                        tss_source = "hg38"
                        )
ETable <- rGREAT::getEnrichmentTable(r.RGL_Astrocyte_age_DAP_list)

#get the different pathway of each subcluster from ETable
GO <- list(ETable.cluster.list[[1]],ETable.cluster.list[[2]],ETable.cluster.list[[3]],ETable.cluster.list[[4]],ETable.cluster.list[[5]])
list <- c("ROBO2 Radial Glia", "SLIT2 Radial Glia", "ROBO2 Astrocyte","SEMA3E Astrocyte","OL-like Astrocyte","Undetermined Astrocyte")

#make annotation dataframe and DF for heatmap
AnnoDF <- data.frame(c("ROBO2 Radial Glia", "SLIT2 Radial Glia", "ROBO2 Astrocyte","SEMA3E Astrocyte","OL-like Astrocyte","Undetermined Astrocyte"))
colnames(AnnoDF) <- c("Subcluster")
AnnoDF$Subcluster <- factor(AnnoDF$Subcluster, levels = c("ROBO2 Radial Glia", "SLIT2 Radial Glia", "ROBO2 Astrocyte","SEMA3E Astrocyte","OL-like Astrocyte","Undetermined Astrocyte"))
colAnno <- HeatmapAnnotation(
  df=AnnoDF,
  show_annotation_name = c(TRUE),
  annotation_name_gp = gpar(fontsize = 12),
  annotation_name_side = "left",
  col = list(Subcluster = c("ROBO2 Radial Glia" = "#e2e700","SLIT2 Radial Glia" = "#FFDAB9", "ROBO2 Astrocyte" = "#FFA500","SEMA3E Astrocyte" = "#FF4F00","OL-like Astrocyte" = "#C2A162","Undetermined Astrocyte" = "#BDC3C7")))

names(GO) <- list
Desc_list <- lapply(list, function(x){
df <- GO[[x]]
df <- df[df$p_value < 0.05,]
df <- df[order(df$p_value, decreasing = FALSE),]
desc <- df$id
desc <- desc[1:5]
return(desc)
}
)

Desc <- unlist(Desc_list) %>% unique()
Desc.df <- as.data.frame(Desc)
Desc.df <- na.omit(Desc.df)
rownames(Desc.df) <- Desc.df$Desc
Desc <- na.omit(Desc)
cols <-lapply(list, function(great){
  Desc.df[great] <- 0
  great.Desc.df <- data.frame(GO[[great]])
  sig <-data.frame(great.Desc.df[great.Desc.df$p_value < 0.05,]) 
  sig <- sig[order(sig$p_value, decreasing = F),]
  Desc.df[sig$id,great]<- great.Desc.df[great.Desc.df$id %in% sig$id, "fold_enrichment"]
  Desc.df <- Desc.df[unique(Desc),] 
  rownames(Desc.df) <- Desc.df$Desc
  Desc.df$Desc <- NULL
  return(Desc.df)
  })
df2 <- data.frame(cols)
matrix_GO <- as.matrix(df2)
colnames(matrix_GO) <- colnames(df2)
rownames(matrix_GO) <- unique(Desc)
matrix_GO = t(apply(df2, 1, scale))

#to draw GO heatmap
plot_GO <- Heatmap(matrix_GO, cluster_columns=F,cluster_rows =FALSE
                       , row_order = Desc, row_names_gp = gpar(fontsize = 5),top_annotation = colAnno, show_column_names = TRUE)
draw(plot_GO)
```

```{r Supplemental Figure 2G}
##compute the GC content for each peak
DefaultAssay(RGL_Astrocyte_harmony) <- "ATAC"
RGL_Astrocyte_harmony <- RegionStats(RGL_Astrocyte_harmony, genome = BSgenome.Hsapiens.UCSC.hg38)

#link peaks to genes
RGL_Astrocyte_harmony <- LinkPeaks(
  object = RGL_Astrocyte_harmony,
  peak.assay = "ATAC",
  expression.assay = "RNA",
  genes.use = "FBXO17")

##to visualize open peaks, RNA expression and links on CoveragePlot
CoveragePlot(
  object = RGL_Astrocyte_harmony,
  region = c("chr3-147396884-147397792"),
  features = c("ZIC1","ZIC4"),
  group.by = "dev.group",
  expression.assay = "RNA",
  extend.upstream = 20000,
  extend.downstream = 20000) & scale_fill_manual(values = devcolor) & theme(
  panel.background = element_rect(fill = "#D3D3D3",
                                colour = "#D3D3D3"))
```












